/* Canon event dates are separate from the deliberately elastic drawing coordinates.
   Political weights are editorial drawing values, never measurements or percentages. */
window.HISTOMAP = {
  height:3460,
  anchors:[[-500,110],[-382,225],[-232,345],[-230,450],[-228,540],[-132,660],[-100,740],[-32,880],[-24,985],[-22,1080],[-20,1190],[-19,1310],[-18,1390],[-10,1570],[-9,1650],[-5,1770],[-2,1900],[-1,1990],[0,2130],[3,2290],[4,2420],[5,2560],[9,2690],[28,2850],[34,3060],[35,3370]],
  eras:[
    {id:'high',name:'The High Republic',short:'High Republic',range:'c. 500–100 BBY',start:-500,end:-100,y:110},
    {id:'fall',name:'Fall of the Jedi',short:'Fall of the Jedi',range:'100–19 BBY',start:-100,end:-19,y:740},
    {id:'empire',name:'Reign of the Empire',short:'Imperial reign',range:'19 BBY–0',start:-19,end:0,y:1310},
    {id:'rebellion',name:'Age of Rebellion',short:'Galactic Civil War',range:'0–5 ABY · focus',start:0,end:5,y:2130},
    {id:'new',name:'The New Republic',short:'New Republic',range:'5–34 ABY',start:5,end:34,y:2560},
    {id:'order',name:'Rise of the First Order',short:'First Order war',range:'34–35 ABY · focus',start:34,end:36,y:3060}
  ],
  sources:{
    eras:['Official Star Wars eras','https://www.starwars.com/eras'],
    chronology:['Canon chronology · Space.com','https://www.space.com/star-wars-timeline'],
    dates:['Canon media timeline · Wookieepedia','https://starwars.fandom.com/wiki/Timeline_of_canon_media'],
    high:['The High Republic · official reading guide','https://www.starwars.com/news/every-star-wars-the-high-republic-book-and-comic-series'],
    republic:['Galactic Republic · Databank','https://www.starwars.com/databank/galactic-republic/'],
    separatists:['Separatists · Databank','https://www.starwars.com/databank/confederacy-of-independent-systems/'],
    empire:['Galactic Empire · Databank','https://www.starwars.com/databank/galactic-empire'],
    mothma:['Mon Mothma · Databank','https://www.starwars.com/databank/mon-mothma'],
    newRepublic:['New Republic · Databank','https://www.starwars.com/databank/the-new-republic'],
    firstOrder:['First Order · Databank','https://www.starwars.com/databank/the-first-order'],
    resistance:['Resistance · Databank','https://www.starwars.com/databank/the-resistance'],
    jedi:['Jedi Order · Databank','https://www.starwars.com/databank/jedi-order'],
    luke:['Luke Skywalker · Databank','https://www.starwars.com/databank/luke-skywalker'],
    rey:['Rey · Databank','https://www.starwars.com/databank/rey'],
    sith:['Sith · Databank','https://www.starwars.com/databank/sith'],
    nihil:['The Nihil · Databank','https://www.starwars.com/databank/the-nihil'],
    starlight:['Starlight Beacon · Databank','https://www.starwars.com/databank/starlight-beacon'],
    deathstar:['Death Star · Databank','https://www.starwars.com/databank/death-star'],
    jakku:['Jakku · Databank','https://www.starwars.com/databank/jakku'],
    mandalore:['Mandalorian history · StarWars.com','https://www.starwars.com/news/who-are-the-mandalorians'],
    eternal:['Sith Eternal · Databank','https://www.starwars.com/databank/sith-eternal'],
    exegol:['Exegol · Databank','https://www.starwars.com/databank/exegol']
  },
  factions:[
    {id:'republic',name:'Galactic Republic',color:'#d8b76b',label:'GALACTIC REPUBLIC',labels:[[-405,2],[-65,2],[-21,2]],sources:['republic'],text:'A union of member worlds governed through the Senate. In the High Republic it reaches toward the frontier; centuries later, institutional weakness and a manufactured war make it vulnerable to Palpatine.',reading:'Follow the gold stream into the Clone Wars. Its split marks secession; its abrupt change to red marks the conversion of republican institutions into the Empire.',tags:['Coruscant','The Senate','Chancellors'],event:'geonosis'},
    {id:'rebels',name:'Rebel cells → Rebel Alliance',color:'#72bfae',label:'REBEL ALLIANCE',labels:[[-3,1],[2,2]],sources:['mothma'],text:'Resistance begins in scattered networks. Mon Mothma helps bring rebel cells together into an alliance; military victories then give that movement the capacity to establish a government.',reading:'The thread begins as early opposition, not a formally founded Alliance. It broadens toward Yavin and Endor, then becomes the New Republic.',tags:['Mon Mothma','Bail Organa','Leia Organa'],event:'alliance'},
    {id:'newRepublic',name:'New Republic',color:'#82b7c7',label:'NEW REPUBLIC',labels:[[7,2],[22,2]],sources:['newRepublic'],text:'The victorious rebellion builds a Senate and civilian government. The Galactic Concordance ends the main war, while disarmament and political division leave the Republic poorly prepared for the First Order.',reading:'This government grows from the Alliance after Endor. Its institutional stream collapses at Hosnian Prime; that does not mean every member world disappears.',tags:['Restored Senate','Galactic Concordance','Hosnian Prime'],event:'jakku'},
    {id:'resistance',name:'Resistance & allied uprising',color:'#85ceb1',label:'RESISTANCE',labels:[[34.8,1]],sources:['resistance'],text:'Leia organizes a small force to oppose the First Order. It survives devastating defeats and becomes the nucleus around which a much larger civilian fleet and galactic uprising gather.',reading:'The movement branches from the New Republic period but is not its regular army. Its final widening includes independent allies, not a newly established galactic government.',tags:['Leia Organa','Poe Dameron','Civilian allies'],event:'exegol'},
    {id:'empire',name:'Galactic Empire',color:'#bd5d59',label:'GALACTIC EMPIRE',labels:[[-14,2],[-6,2],[1.8,2]],sources:['empire'],text:'Palpatine turns the Republic into an authoritarian state, retaining its administrative machinery and imposing military control. Planetary terror and political repression provoke the rebellion that eventually breaks its central power.',reading:'The red stream inherits the Republic and conquered Separatist space. Endor fractures central rule; Jakku leaves scattered remnants rather than erasing every Imperial force.',tags:['Palpatine','Darth Vader','Imperial military'],event:'empire'},
    {id:'remnant',name:'Imperial remnants',color:'#9a686e',label:'IMPERIAL REMNANTS',labels:[[14,2]],sources:['firstOrder','newRepublic'],text:'Defeat leaves surviving warlords, loyalists, and clandestine networks. Some remain in known space while others build strength in the Unknown Regions.',reading:'This is an aggregate of separate forces. The transition into the First Order is selective and schematic; it does not claim every remnant joined it, or assign one exact founding date.',tags:['Warlords','Unknown Regions','Imperial legacy'],event:'remnants'},
    {id:'firstOrder',name:'First Order',color:'#d47869',label:'FIRST ORDER',labels:[[32,1],[34.3,2]],sources:['firstOrder'],text:'An Imperial successor built in secrecy becomes an open conquering power. The destruction of the New Republic capital allows the First Order to rapidly expand its reach.',reading:'Its early boundary is approximate: the organization develops over years. A related Sith fleet appears alongside it at the end; the two are not the same institution.',tags:['Snoke','Kylo Ren','Starkiller Base'],event:'hosnian'},
    {id:'eternal',name:'Sith Eternal fleet',color:'#af8299',label:'SITH ETERNAL',labels:[],sources:['eternal','exegol'],text:'On Exegol, Palpatine’s cult secretly builds the fleet intended to enforce a new Sith empire. Its public emergence culminates in the Battle of Exegol.',reading:'The political ribbon shows the fleet’s emergence at 35 ABY, not the foundation of the cult. Its longer hidden continuity is represented in the separate Sith track.',tags:['Exegol','Palpatine','Final Order'],event:'exegol'},
    {id:'separatists',name:'Separatist Alliance',color:'#859faf',label:'SEPARATISTS',labels:[[-20.8,1]],sources:['separatists'],text:'The Confederacy of Independent Systems breaks from the Republic. Its droid armies fight the Clone Wars, while its leadership is manipulated by the same Sith conspiracy that controls its opponent.',reading:'This stream pulls away from the Republic, then ends when its leadership is eliminated and the Empire absorbs its power base.',tags:['Count Dooku','General Grievous','Droid armies'],event:'geonosis'},
    {id:'nihil',name:'The Nihil',color:'#a48cb9',label:'NIHIL',labels:[[-231,1]],sources:['nihil','starlight'],text:'Marauders challenge Republic expansion with terror attacks and control over hyperspace travel. The destruction of Starlight Beacon and the Occlusion Zone turn a frontier threat into a major crisis.',reading:'The ribbon highlights the height of the Nihil crisis. Its taper is schematic and does not assert that every Nihil faction vanished on a single date.',tags:['Marchion Ro','Outer Rim','Occlusion Zone'],event:'starlight'},
    {id:'independent',name:'Independent worlds & regional powers',color:'#718b82',label:'INDEPENDENT WORLDS',labels:[[-310,2],[-15,2],[15,2]],sources:['mandalore','eras'],text:'The galaxy contains societies beyond the reach of its largest states: independent systems, Mandalorian factions, Hutt interests, criminal networks, and other regional powers. Their relationships change throughout the saga.',reading:'This grouping is a cartographic simplification, not a single faction or alliance. It also leaves room for the limits of central government and gaps in the story.',tags:['Regional governments','Mandalorian factions','Outer Rim'],event:'mandalore'},
    {id:'jedi',name:'The Jedi tradition',color:'#a9c59b',sources:['jedi'],text:'From public peacekeepers to hunted survivors, then Luke’s students and Rey, the Jedi thread shows a tradition enduring institutional destruction.',reading:'This separate track represents continuity and visibility, not political territory or a count of Jedi. Its narrow surviving line after Order 66 matters as much as its earlier breadth.',tags:['The Force','Survivors','Luke & Rey'],event:'order66'},
    {id:'sith',name:'The Sith tradition',color:'#d28489',sources:['sith','eternal'],text:'Hidden Sith plotting culminates in Sidious’s Empire. After Endor, Palpatine and the Sith Eternal continue in secret on Exegol.',reading:'This is a tradition and conspiracy track, not a population measure. The First Order’s dark-side users are not automatically classified as Sith.',tags:['Rule of Two','Darth Sidious','Sith Eternal'],event:'exegol'}
  ],
  // y, editorial widths in faction order through independent; rows are display knots.
  states:[
    [110,[72,0,0,0,0,0,0,0,0,0,28]],
    [225,[76,0,0,0,0,0,0,0,0,0,24]],
    [320,[76,0,0,0,0,0,0,0,0,0,24]],
    [345,[72,0,0,0,0,0,0,0,0,5,23]],
    [450,[63,0,0,0,0,0,0,0,0,14,23]],
    [500,[61,0,0,0,0,0,0,0,0,16,23]],
    [570,[74,0,0,0,0,0,0,0,0,2,24]],
    [610,[76,0,0,0,0,0,0,0,0,0,24]],
    [740,[76,0,0,0,0,0,0,0,0,0,24]],
    [880,[73,0,0,0,0,0,0,0,0,0,27]],
    [985,[63,0,0,0,0,0,0,0,12,0,25]],
    [1080,[48,0,0,0,0,0,0,0,28,0,24]],
    [1190,[50,0,0,0,0,0,0,0,30,0,20]],
    [1309,[58,0,0,0,0,0,0,0,22,0,20]],
    [1310,[0,0,0,0,80,0,0,0,0,0,20]],
    [1390,[0,1,0,0,81,0,0,0,0,0,18]],
    [1570,[0,2,0,0,82,0,0,0,0,0,16]],
    [1770,[0,4,0,0,80,0,0,0,0,0,16]],
    [1900,[0,9,0,0,75,0,0,0,0,0,16]],
    [2130,[0,14,0,0,70,0,0,0,0,0,16]],
    [2290,[0,12,0,0,72,0,0,0,0,0,16]],
    [2419,[0,21,0,0,63,0,0,0,0,0,16]],
    [2440,[0,30,0,0,28,22,0,0,0,0,20]],
    [2490,[0,0,40,0,20,19,0,0,0,0,21]],
    [2560,[0,0,56,0,0,19,0,0,0,0,25]],
    [2690,[0,0,61,0,0,16,0,0,0,0,23]],
    [2790,[0,0,62,0,0,14,0,0,0,0,24]],
    [2850,[0,0,55,3,0,4,13,0,0,0,25]],
    [2970,[0,0,51,4,0,3,18,0,0,0,24]],
    [3059,[0,0,48,5,0,3,21,0,0,0,23]],
    [3080,[0,0,0,7,0,3,59,0,0,0,31]],
    [3180,[0,0,0,2,0,2,67,0,0,0,29]],
    [3260,[0,0,0,5,0,2,62,0,0,0,31]],
    [3330,[0,0,0,9,0,2,50,8,0,0,31]],
    [3370,[0,0,0,20,0,2,35,12,0,0,31]],
    [3400,[0,0,0,45,0,2,8,0,0,0,45]],
    [3460,[0,0,0,45,0,2,8,0,0,0,45]]
  ],
  events:[
    {id:'frontier',year:-382,title:'An expanding frontier',level:2,faction:'republic',text:'Jedi and Republic explorers reach farther into the Outer Rim. The Path of the Open Hand challenges the Jedi’s relationship with the Force.',effect:'Expansion brings the Republic into contact and conflict with worlds beyond its established reach.',media:['The High Republic · Phase II'],sources:['high']},
    {id:'disaster',year:-232,title:'The Great Disaster',level:1,faction:'nihil',text:'A hyperspace catastrophe threatens inhabited systems. Jedi coordinate a vast rescue as the Nihil emerge as a dangerous opponent.',effect:'The Republic’s optimistic expansion meets a threat that exploits the routes binding the galaxy together.',media:['Light of the Jedi'],sources:['nihil','high']},
    {id:'beacon',year:-232,y:395,title:'Starlight shines',level:3,faction:'republic',text:'Starlight Beacon opens as a Republic outpost and symbol of connection between the Core and frontier.',effect:'A public investment in unity also creates a conspicuous target.',media:['The High Republic · Phase I'],sources:['starlight']},
    {id:'starlight',year:-230,title:'Starlight falls',level:1,faction:'nihil',text:'The Nihil sabotage Starlight Beacon above Eiram. The station’s destruction strikes at both the Jedi and the Republic’s promise of protection.',effect:'The frontier crisis deepens. The Nihil’s subsequent Occlusion Zone cuts worlds off from Republic access.',media:['The Fallen Star','The High Republic · Phase III'],sources:['starlight','nihil']},
    {id:'acolyte',year:-132,title:'A shadow in the Force',level:2,faction:'sith',text:'Murders draw Jedi into an investigation that exposes concealed failures and a dark-side threat.',effect:'The map’s hidden Sith thread continues alongside a still-powerful Jedi institution.',media:['The Acolyte'],sources:['chronology'],note:'The story reveals a hidden threat; it is not the public return of the Sith recognized by the Jedi Council.'},
    {id:'naboo',year:-32,title:'The Naboo crisis',level:1,faction:'republic',text:'The Trade Federation invades Naboo. Palpatine rises to the chancellorship while Darth Maul’s appearance reveals that the Sith have returned.',effect:'A local crisis becomes a decisive shift in the leadership of the Republic.',media:['I · The Phantom Menace'],sources:['republic','chronology']},
    {id:'secession',year:-24,title:'The Separatist break',level:3,faction:'separatists',text:'Dooku’s secession movement draws worlds away from the Republic, preparing the political division that becomes the Clone Wars.',effect:'A new political stream branches from the Republic before open war begins.',media:['Pre–Clone Wars background'],sources:['separatists'],approx:true,note:'Placed around 24 BBY to show the developing movement; secession was a process, not one simultaneous departure.'},
    {id:'geonosis',year:-22,title:'The Clone Wars begin',level:1,faction:'separatists',text:'Republic clones and Separatist droids clash at Geonosis. The Jedi become military commanders in a war whose opposing leaders are being manipulated by Sidious.',effect:'The Republic divides into rival war machines while emergency power accumulates around its Chancellor.',media:['II · Attack of the Clones','The Clone Wars'],sources:['separatists','republic']},
    {id:'mandalore',year:-19,y:1240,title:'The Siege of Mandalore',level:3,faction:'independent',text:'Ahsoka and allied Mandalorians confront Maul as the Clone Wars reach their final days.',effect:'Mandalore’s internal conflicts intersect with the collapse of the Republic, showing why regional histories do not fit neatly into two sides.',media:['The Clone Wars · Season 7'],sources:['mandalore','dates']},
    {id:'order66',year:-19,y:1295,title:'Order 66',level:1,faction:'jedi',text:'Palpatine turns the clone army against the Jedi. Anakin joins the Sith as Darth Vader, and survivors of the purge are driven into hiding.',effect:'The Jedi institution collapses almost overnight. Its surviving tradition remains as a thin, continuous thread.',media:['III · Revenge of the Sith','The Clone Wars'],sources:['jedi']},
    {id:'empire',year:-19,y:1350,title:'The Empire is declared',level:1,faction:'empire',text:'Palpatine reorganizes the Republic into the Galactic Empire. Separatist leaders are killed and their power base is absorbed into the new order.',effect:'Gold becomes red: this is a takeover of the existing state, not the arrival of a foreign civilization.',media:['III · Revenge of the Sith'],sources:['empire','separatists']},
    {id:'solo',year:-10,title:'Life at the margins',level:3,faction:'independent',text:'Han Solo’s early adventures move through Imperial recruitment, exploited frontier worlds, and powerful crime syndicates.',effect:'The independent-worlds band includes criminal and regional power that coexists with Imperial rule.',media:['Solo · A Star Wars Story'],sources:['chronology','dates']},
    {id:'kenobi',year:-9,title:'Jedi in hiding',level:2,faction:'jedi',text:'Obi-Wan emerges from exile to protect Leia and confronts Vader. The Inquisitors continue hunting survivors.',effect:'The Jedi thread is diminished, but knowledge and personal connections survive the purge.',media:['Obi-Wan Kenobi'],sources:['jedi','dates']},
    {id:'andor',year:-5,title:'The sparks of rebellion',level:2,faction:'rebels',text:'Local resistance, covert organizers, and emerging rebel cells begin to connect. Cassian Andor and the Ghost crew inhabit different parts of this growing opposition.',effect:'Scattered acts of resistance gradually become an organized challenge.',media:['Andor · Season 1','Rebels · early seasons'],sources:['mothma','dates']},
    {id:'alliance',year:-2,title:'The Alliance unites',level:1,faction:'rebels',text:'After condemning Imperial violence, Mon Mothma escapes arrest and calls for rebel cells to unite.',effect:'Separate networks coalesce into a shared political and military movement.',media:['Andor · Season 2','Rebels · Secret Cargo'],sources:['mothma','dates']},
    {id:'scarif',year:0,y:2045,title:'The sacrifice at Scarif',date:'0 BBY · before Yavin',level:2,faction:'rebels',text:'Rogue One secures and transmits the Death Star plans at the cost of the team’s lives.',effect:'A local operation creates the possibility of defeating the Empire’s greatest weapon.',media:['Rogue One · A Star Wars Story'],sources:['mothma','deathstar']},
    {id:'alderaan',year:0,y:2087,title:'Alderaan destroyed',date:'0 BBY · before Yavin',level:3,faction:'empire',text:'The Death Star destroys Alderaan in a demonstration of Imperial terror.',effect:'The regime’s promise of absolute control is made brutally visible.',media:['IV · A New Hope'],sources:['deathstar']},
    {id:'yavin',year:0,title:'The Battle of Yavin',date:'0 · the calendar’s anchor',level:1,faction:'rebels',text:'Luke Skywalker destroys the first Death Star, saving the rebel base and demonstrating that the Empire can be defeated.',effect:'The rebellion gains a defining victory. This battle is the reference point for BBY and ABY dates.',media:['IV · A New Hope'],sources:['deathstar']},
    {id:'hoth',year:3,title:'The retreat from Hoth',level:2,faction:'empire',text:'Imperial forces drive the rebels from Echo Base. The Alliance survives by dispersing rather than defending one fixed capital.',effect:'Rebel influence dips without ending the movement’s continuity.',media:['V · The Empire Strikes Back'],sources:['chronology','dates']},
    {id:'endor',year:4,title:'The Battle of Endor',level:1,faction:'rebels',text:'The second Death Star is destroyed. Vader turns against Palpatine to save Luke, and Imperial central authority begins to break apart.',effect:'The Empire fractures into remnants while the victorious rebellion moves toward government.',media:['VI · Return of the Jedi'],sources:['luke','mothma','dates']},
    {id:'new-republic',year:4,y:2490,title:'A Republic rebuilt',level:2,faction:'newRepublic',text:'The Alliance gives way to a new republican government and a restored Senate.',effect:'A resistance movement becomes a state, while the wider war continues.',media:['Aftermath era'],sources:['newRepublic','mothma']},
    {id:'jakku',year:5,title:'Jakku & the Concordance',level:1,faction:'newRepublic',text:'The Empire’s last major stand ends at Jakku. The Galactic Concordance formalizes peace between the New Republic and the defeated Imperial state.',effect:'The main war ends. Remnants and hidden networks persist beyond the treaty.',media:['Aftermath · Empire’s End','Battlefront II'],sources:['jakku','newRepublic','dates']},
    {id:'remnants',year:9,title:'A fragile peace',level:2,faction:'remnant',approx:true,text:'Imperial warlords and secret projects endure while the New Republic works to consolidate peace. Din Djarin and Grogu travel through this unsettled galaxy.',effect:'The map keeps a remnant stream alive: Endor and Jakku were not the end of every Imperial organization.',media:['The Mandalorian · early seasons'],sources:['eras','firstOrder','dates'],note:'Around 9 ABY marks the beginning of this screen-story period. Later connected series are not all assigned this exact year.'},
    {id:'resistance',year:28,title:'Leia forms the Resistance',level:2,faction:'resistance',text:'Leia builds an independent force to investigate and resist the First Order as many New Republic leaders underestimate the danger.',effect:'A small opposition stream branches within the New Republic era.',media:['Bloodline'],sources:['resistance','dates']},
    {id:'temple',year:28,y:2910,title:'Luke’s temple falls',level:3,faction:'jedi',text:'Luke’s attempt to restore the Jedi ends in catastrophe as Ben Solo falls to the dark side. Luke withdraws to Ahch-To.',effect:'The renewed institution collapses; the Jedi legacy survives outside its walls.',media:['The Rise of Kylo Ren','The Last Jedi · backstory'],sources:['luke','dates']},
    {id:'hosnian',year:34,title:'Hosnian Prime destroyed',level:1,faction:'firstOrder',text:'Starkiller Base annihilates the Hosnian system, destroying the New Republic’s capital and central leadership.',effect:'The First Order exploits the institutional collapse to launch its conquest.',media:['VII · The Force Awakens'],sources:['firstOrder','dates']},
    {id:'starkiller',year:34,y:3115,title:'Starkiller Base falls',level:2,faction:'resistance',text:'The Resistance destroys Starkiller Base, but the wider First Order military remains capable of pursuing its enemies.',effect:'Destroying a superweapon does not by itself reverse the collapse of the Republic.',media:['VII · The Force Awakens'],sources:['resistance']},
    {id:'crait',year:34,y:3180,title:'The last stand on Crait',level:2,faction:'resistance',text:'Luke’s final intervention gives the surviving Resistance time to escape. Rey carries the Jedi texts into an uncertain future.',effect:'The Resistance contracts to a handful of survivors, while a renewed Jedi thread continues through Rey.',media:['VIII · The Last Jedi'],sources:['luke','rey','resistance']},
    {id:'sith-fleet',year:35,y:3305,title:'The hidden fleet emerges',level:3,faction:'eternal',text:'Palpatine reveals the forces assembled by the Sith Eternal on Exegol and seeks to combine them with the First Order.',effect:'A separate military stream emerges from the long-hidden Sith conspiracy.',media:['IX · The Rise of Skywalker'],sources:['eternal','exegol']},
    {id:'exegol',year:35,title:'Exegol & the uprising',level:1,faction:'resistance',text:'Rey confronts Palpatine while the Resistance and a vast civilian fleet attack the Sith Eternal. The victory accompanies uprisings against First Order rule across the galaxy.',effect:'Centralized conquest breaks down. The map ends with allied resistance and liberated worlds, without inventing the government that follows.',media:['IX · The Rise of Skywalker'],sources:['rey','eternal','dates']}
  ]
};
