from pathlib import Path
import re

p=Path('StarWars/recurring-lifelines.js')
s=p.read_text()

blurbs={
'r2d2': "R2-D2 is an astromech droid whose stubborn initiative repeatedly changes galactic history, from the Naboo crisis and Clone Wars to the Rebellion and Resistance. He carries plans, messages, memories, and people through political systems that rise and fall around him, making him one of the saga’s clearest witnesses across generations.",
'c3po': "C-3PO is a protocol droid built by Anakin Skywalker whose long service to the Skywalker family carries him from the late Republic through the Resistance. Frequently anxious but unexpectedly durable, he survives wars, regime changes, memory loss, and repeated separations while remaining a connective thread between otherwise distant eras.",
'palpatine': "Sheev Palpatine is the Sith Lord Darth Sidious, who converts a constitutional republic into a dictatorship by manufacturing crises, controlling both sides of the Clone Wars, and destroying the Jedi Order. His rule as Emperor defines the Imperial era, and his later return behind the Final Order shows how far the consequences of his project extend beyond his apparent death at Endor.",
'maul': "Maul begins as Darth Sidious’s weapon but survives his presumed death to become an independent force in the galaxy’s criminal and political underworld. His attempts to build power through syndicates, Mandalore, and personal vendettas turn him into a bridge between the fall of the Republic, the rise of the Empire, and the early Rebellion.",
'mace': "Mace Windu is one of the Jedi Council’s most powerful and influential Masters, serving as both statesman and general during the Republic’s final years. His determination to stop Darth Sidious places him at the decisive confrontation where Anakin Skywalker chooses Palpatine over the Jedi, accelerating the Order’s destruction.",
'dooku': "Count Dooku is a former Jedi Master who becomes Darth Tyranus, Sidious’s apprentice and the public leader of the Confederacy of Independent Systems. His aristocratic separatist movement gives political legitimacy to a war secretly engineered by the Sith, making him central to the mechanism that destroys the Republic he once served.",
'boba': "Boba Fett is an unaltered clone of Jango Fett who grows from a child shaped by the Clone Wars into one of the galaxy’s most feared bounty hunters. After surviving the Sarlacc, he shifts from hired enforcer to would-be crime lord on Tatooine, giving his story an unusual path from Republic-era cloning to the post-Imperial underworld.",
'bail': "Bail Organa is an Alderaanian senator who resists Palpatine’s authoritarianism from inside the Republic before helping build the Rebel Alliance in secret. By raising Leia, protecting surviving Jedi, and connecting scattered opposition networks, he becomes one of the principal institutional links between the old Republic and the Rebellion.",
'tarkin': "Wilhuff Tarkin is a Republic officer who embraces increasingly centralized military power and rises to become one of the Empire’s most important governors. His career tracks the state’s transformation from wartime Republic to authoritarian Empire, culminating in his command of the Death Star and the doctrine of rule through fear.",
'mon': "Mon Mothma is a Republic senator who gradually moves from parliamentary opposition to covert resistance and ultimately becomes a principal founder of the Rebel Alliance. After the Empire’s defeat she helps lead the restored New Republic, making her life one of the strongest political through-lines from the late Republic into the post-Imperial order.",
'saw': "Saw Gerrera is an Onderonian resistance fighter whose experience fighting occupation turns him into one of the galaxy’s most uncompromising insurgents. He shares the Rebellion’s enemy but rejects much of its restraint, illustrating the moral and strategic fracture lines inside anti-Imperial resistance.",
'grievous': "General Grievous is the cyborg Supreme Martial Commander of the Separatist droid armies and the most visible military antagonist of the Republic late in the Clone Wars. His campaigns keep the Jedi consumed by conventional war while Sidious’s deeper plan moves toward Order 66 and the destruction of both sides’ political leadership.",
'grandinq': "The Grand Inquisitor is a former Jedi Temple Guard who turns against the Order and becomes the senior hunter of surviving Jedi under Darth Vader. His role shows how the Empire repurposes fallen or corrupted Force users into instruments for erasing the institutional remnants of the Jedi.",
'ackbar': "Gial Ackbar is a Mon Calamari military leader whose fight for his own world develops into service at the highest levels of the Rebel Alliance. Decades later he returns to command for the Resistance, linking two generations of organized opposition to authoritarian galactic powers.",
'wedge': "Wedge Antilles is a Rebel starfighter pilot who survives both Death Star battles and becomes one of the Alliance’s most dependable combat veterans. His later return during the war against the Final Order turns an ordinary human pilot into a quiet connective thread between the Rebellion and the galaxy’s next resistance movement.",
'bb8': "BB-8 is a Resistance astromech whose mission carrying the map to Luke Skywalker draws Rey, Finn, and Poe Dameron into the same conflict. Like R2-D2 before him, he functions as both companion and courier, moving crucial information through a war in which small acts repeatedly alter strategic outcomes.",
'bokatan': "Bo-Katan Kryze is a Mandalorian warrior whose political identity changes repeatedly as Mandalore passes through civil war, Imperial occupation, diaspora, and attempted restoration. Her alliances with Ahsoka Tano, the Rebellion-era resistance, and Din Djarin make her one of the clearest character-level guides to Mandalorian history across decades.",
'rex': "Captain Rex is a clone officer who serves beside Anakin Skywalker and Ahsoka Tano through much of the Clone Wars before surviving Order 66 with his autonomy restored. His later participation in the Rebellion gives the clone generation a direct human link to the struggle against the Empire they were created to help bring about.",
'hera': "Hera Syndulla is a Twi’lek pilot and rebel organizer who helps turn a small insurgent cell into part of the wider Rebel Alliance. Her later service as a New Republic general shows the difficult transition from revolutionary resistance to governing institutions after the Empire’s defeat.",
'chopper': "C1-10P, better known as Chopper, is Hera Syndulla’s irritable astromech and a veteran of the Ghost crew’s campaigns against the Empire. His survival into the New Republic era makes him another unusually persistent witness to the shift from localized rebellion to galactic regime change.",
'fennec': "Fennec Shand is an elite assassin and mercenary whose career spans the early Imperial period and the unstable years after the Empire’s fall. Her partnership with Boba Fett places her at the intersection of bounty hunting, criminal power, and the reordering of the Outer Rim underworld.",
'cadbane': "Cad Bane is a Duros bounty hunter whose reputation is built during the Clone Wars through work for criminals, Separatists, and other powerful clients. His survival into the post-Imperial era makes him a rare underworld figure whose career directly connects the Republic’s collapse with the later struggle for control of Tatooine.",
'din': "Din Djarin is a Mandalorian bounty hunter whose protection of Grogu draws him into conflicts involving Imperial remnants, the New Republic, and competing visions of Mandalorian identity. His journey shifts from personal survival to family, community, and the wider question of what Mandalore can become after Imperial devastation.",
'zeb': "Garazeb Orrelios is a Lasat survivor of Imperial violence who becomes a core member of the Ghost crew and an early Rebel Alliance fighter. His later appearance in New Republic service shows a former insurgent continuing to defend the political order that the Rebellion helped create.",
'huyang': "Huyang is an ancient architect droid who has instructed generations of Jedi in lightsaber construction, giving him institutional memory stretching far beyond most living characters. His survival from the High Republic era into Ahsoka Tano’s post-Imperial journey makes him a literal repository of Jedi history after the Order itself has been shattered.",
'thrawn': "Grand Admiral Thrawn is a Chiss strategist whose analytical brilliance makes him one of the Empire’s most dangerous commanders despite his outsider status. His disappearance with Ezra Bridger removes him from the Galactic Civil War, while his return in the New Republic era threatens to reunify Imperial remnants around a leader capable of strategic coordination.",
'yularen': "Wullf Yularen begins as a Republic admiral working closely with Jedi commanders during the Clone Wars and later becomes a senior officer in the Imperial Security Bureau. His career demonstrates how professional institutions and personnel from the Republic can be absorbed directly into the machinery of the Empire.",
'jabba': "Jabba Desilijic Tiure is a Hutt crime lord whose influence on Tatooine and across hyperspace routes persists from the late Republic into the Galactic Civil War. His court represents a durable form of non-state power that survives regime change until Leia Organa kills him during the rescue of Han Solo.",
'hux': "Armitage Hux is a First Order general raised inside the authoritarian military culture that grows from Imperial remnants. His rivalry with Kylo Ren and eventual betrayal of the regime expose the personal resentment and institutional instability beneath the First Order’s disciplined exterior.",
'marrok': "Marrok is an armored dark-side warrior associated with the Inquisitorius tradition whose appearances now span multiple stories across the Imperial and post-Imperial chronology. The character’s recurring presence makes him useful less as a political actor than as evidence of how Imperial methods of hunting Force users continue to echo after the Empire’s formal collapse."
}

for ident, blurb in blurbs.items():
    pattern=re.compile(r"^(\s*\['"+re.escape(ident)+r"'.*?,)'[^']*'(\s*(?:,\{.*\})?\],?\s*)$",re.M)
    s2,n=pattern.subn(lambda m:m.group(1)+repr(blurb)+m.group(2),s,count=1)
    if n!=1:
        raise SystemExit(f'Could not replace blurb for {ident}: {n}')
    s=s2

p.write_text(s)
print(f'Enriched {len(blurbs)} recurring-character blurbs')
